const allRoles = {
  accountant: [
    "submitInvoice",
    "getInvoiceById",
    "getBillNum",
    "searchInvoice",
    "searchInvoiceByNum",
    "searchInvoiceByName",
  ],
  admin: [
    "submitInvoice",
    "getInvoiceById",
    "deleteInvoice",
    "searchInvoice",
    "searchInvoiceByNum",
    "searchInvoiceByName",
    "updateInvoice",
    "getBillNum",
    "getAllBooks",
    "getBooks",
    "addBooks",
    "deleteBooks",
    "updateBooks",
    "getPublication",
    "getPublications",
    "addPublications",
    "deletePublications",
    "updatePublication",
    "getUsers",
    "getUser",
    "updateUsers",
    "deleteUser",
    "exportData",
  ],
  super_admin: [
    "submitInvoice",
    "getInvoiceById",
    "deleteInvoice",
    "searchInvoice",
    "searchInvoiceByNum",
    "searchInvoiceByName",
    "updateInvoice",
    "getBillNum",
    "getAllBooks",
    "getBooks",
    "addBooks",
    "deleteBooks",
    "updateBooks",
    "getPublication",
    "getPublications",
    "addPublications",
    "deletePublications",
    "updatePublication",
    "getUsers",
    "getUser",
    "updateUsers",
    "deleteUser",
    "upload",
    "exportData",
  ],
};

const roles = Object.keys(allRoles);
const roleRights = new Map(Object.entries(allRoles));

module.exports = {
  roles,
  roleRights,
};
