export const classList: any = [
  {id: 1, name: 'pre-nursery', value: 'Pre Nursery'},
  {id: 2, name: 'nursery', value: 'Nursery'},
  {id: 1, name: 'infant', value: 'Infant'},
  {id: 3, name: 'prep', value: 'Preparatory'},
  {id: 4, name: 'one', value: '1'},
  {id: 5, name: 'two', value: '2'},
  {id: 6, name: 'three', value: '3'},
  {id: 7, name: 'four', value: '4'},
  {id: 8, name: 'five', value: '5'},
  {id: 9, name: 'six', value: '6'},
  {id: 10, name: 'seven', value: '7'},
  {id: 11, name: 'eight', value: '8'},
  {id: 12, name: 'nine', value: '9'},
  {id: 13, name: 'ten', value: '10'},
  {id: 14, name: 'eleven', value: '11'},
  {id: 14, name: 'twelve', value: '12'},
];
export const dashBorardClassList: any = [
  {id: 1, name: 'pre-nursery', value: 'Pre Nursery', className: 'Pre Nursery'},
  {id: 2, name: 'nursery', value: 'Nursery', className: 'Nursery'},
  {id: 1, name: 'infant', value: 'Infant', className: 'Infant'},
  {id: 3, name: 'prep', value: 'Preparatory', className: 'Preparatory'},
  {id: 4, name: 'one', value: '1', className: 'One'},
  {id: 5, name: 'two', value: '2', className: 'Two'},
  {id: 6, name: 'three', value: '3', className: 'Three'},
  {id: 7, name: 'four', value: '4', className: 'Four'},
  {id: 8, name: 'five', value: '5', className: 'Five'},
  {id: 9, name: 'six', value: '6', className: 'Six'},
  {id: 10, name: 'seven', value: '7', className: 'Seven'},
  {id: 11, name: 'eight', value: '8', className: 'Eight'},
  {id: 12, name: 'nine', value: '9', className: 'Nine'},
  {id: 13, name: 'ten', value: '10', className: 'Ten'},
  {id: 14, name: 'eleven', value: '11', className: 'Eleven'},
  {id: 14, name: 'twelve', value: '12', className: 'Twelve'},
];
